Expansion in plain json
VNG-Realisatie/gemma-zaken pull request #2192
Opened 2023-02-23 14:42 UTC by HenriKorver

2023-03-23 15:13 UTC, HenriKorver commented
Een beschrijving van het expand-mechanisme in plain json aan de hand van voorbeelden is [hier](https://github.com/VNG-Realisatie/gemma-zaken/discussions/1960#discussioncomment-3662403) beschreven.

2023-03-23 15:15 UTC, HenriKorver commented
Deze pull request hoort bij issue #2205.

2023-03-23 15:19 UTC, HenriKorver commented
@MatthijsBekendam Kun jij een start maken om het expand-mechanisme in de referentie-implementatie te implementeren?

2023-03-29 07:39 UTC, HenriKorver commented
@MatthijsBekendam Zie [hier](https://redocly.github.io/redoc/?nocors&url=https://raw.githubusercontent.com/VNG-Realisatie/gemma-zaken/HenriKorver-expansion/api-specificatie/DESIGN/zaken/1.4.x/openapi.yaml#tag/zaken/operation/zaak_retrieve) met het expand mechanisme in Redoc. Deze OAS is onderdeel van deze PR.

2023-04-17 13:40 UTC, michielverhoef commented on api-specificatie/DESIGN/zaken/1.4.x/openapi.yaml
> +  version: 1.4.1
```suggestion
  version: 1.5.0
```

2023-04-17 13:42 UTC, michielverhoef commented on api-specificatie/DESIGN/zaken/1.4.x/openapi.yaml
> +            $ref: '#/components/schemas/ZaakExpanded'
Ik zou hier alleen een Zaak van maken. Anders loop je het risico wel heel veel informatie tegelijk op te halen. Wil je meer info over die specifieke zaak dan kun je die zaak met expand ophalen.

2023-04-17 13:42 UTC, michielverhoef commented on api-specificatie/DESIGN/zaken/1.4.x/openapi.yaml
> +            $ref: '#/components/schemas/ZaakExpanded'
Ik zou ook hier alleen een Zaak van maken. Anders loop je het risico wel heel veel informatie tegelijk op te halen. Wil je meer info over die specifieke zaak dan kun je die zaak met expand ophalen.

2023-04-17 13:47 UTC, michielverhoef commented on api-specificatie/DESIGN/zaken/1.4.x/openapi.yaml
> +          $ref: '#/components/schemas/ZaakExpanded'
Betekent dit dat we de Zaak expanded meekrijgen bij het opvragen van een ROL? Dat zou ik niet doen. Laten we met het expand mechanisme juist bewegen naar het bewerken van de Zaak en bijbehorende properties (inclusief groepsattributen zoals ROL, Status, etc.)

2023-04-17 13:47 UTC, michielverhoef requested changes
In de REDOC weergave zie ik veel wijzigingen niet teruigkomen. Verder ben ik het niet met alle voorgestelde keuzes eens.

2023-08-22 08:01 UTC, michielverhoef approved these changes

2023-08-22 08:03 UTC, merged